[tools]
deno = "latest"
go = "latest"
node = "lts"
python = "3.14"
ruby = "latest"
rust = "stable"
uv = "latest"
"github:lynaghk/vibe" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:opencode-ai" = "latest"
"npm:pnpm" = "latest"
"pipx:it2" = "latest"
"pipx:yt-dlp" = "latest"

[settings]
ruby.compile = false
disable_hints = ["*"]
